/* tslint:disable */
/* eslint-disable */
/**
 * Cat API
 * ![cat-api-logo](https://thecatapi.com/_app/immutable/assets/thecatapi-logo.78868573.svg)  ## An open, free, read & write API all about Cats The Cat API gives you access to 10000\'s of Cat images, and breeds. - Upload your own Images - Get detailed info on all Cat Breeds - Allow your Users to Favourite or Vote on Images - Save a custom value with each request so you can match data to your Users  ## How do i get access? Just sign up for an API Key from https://thecatapi.com for free. We\'re looking forward to seeing what you build! Don\'t forget to checkout it\'s sister API - TheDogAPI.com
 *
 * The version of the OpenAPI document: 1.6.3
 * Contact: aden@thatapicompany.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImagesListSearchOrRandom200ResponseInner
 */
export interface ImagesListSearchOrRandom200ResponseInner {
    /**
     * 
     * @type {string}
     * @memberof ImagesListSearchOrRandom200ResponseInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ImagesListSearchOrRandom200ResponseInner
     */
    url?: string;
    /**
     * 
     * @type {number}
     * @memberof ImagesListSearchOrRandom200ResponseInner
     */
    width?: number;
    /**
     * 
     * @type {number}
     * @memberof ImagesListSearchOrRandom200ResponseInner
     */
    height?: number;
}

/**
 * Check if a given object implements the ImagesListSearchOrRandom200ResponseInner interface.
 */
export function instanceOfImagesListSearchOrRandom200ResponseInner(value: object): value is ImagesListSearchOrRandom200ResponseInner {
    return true;
}

export function ImagesListSearchOrRandom200ResponseInnerFromJSON(json: any): ImagesListSearchOrRandom200ResponseInner {
    return ImagesListSearchOrRandom200ResponseInnerFromJSONTyped(json, false);
}

export function ImagesListSearchOrRandom200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImagesListSearchOrRandom200ResponseInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'url': json['url'] == null ? undefined : json['url'],
        'width': json['width'] == null ? undefined : json['width'],
        'height': json['height'] == null ? undefined : json['height'],
    };
}

export function ImagesListSearchOrRandom200ResponseInnerToJSON(json: any): ImagesListSearchOrRandom200ResponseInner {
    return ImagesListSearchOrRandom200ResponseInnerToJSONTyped(json, false);
}

export function ImagesListSearchOrRandom200ResponseInnerToJSONTyped(value?: ImagesListSearchOrRandom200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'url': value['url'],
        'width': value['width'],
        'height': value['height'],
    };
}

